#!/bin/sh

STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|tsx|js|jsx|css|json)$')

if [ -n "$STAGED" ]; then
  echo "$STAGED" | xargs bunx prettier --write
  echo "$STAGED" | xargs git add
fi